### PR TITLE
Changing HttpTracing to TraceContextHolder class as this will have cu…

### LINKED ISSUE #14: TracingPropagationExecInitializer searching for wrong class in registry entries.
`init` function in TracingPropagationExecInitializer is trying to get `HttpTracing.class` from the execution object i pass but instead it should `maybeGet(TraceContextHolder.class)`.
Since in my registry entries only this is present.
```RegistryEntry{type=ratpack.zipkin.internal.RatpackCurrentTraceContext$TraceContextHolder, value=ratpack.zipkin.internal.RatpackCurrentTraceContext$TraceContextHolder@6139672b}```.
Hence httpTracing  is always null in `init`.

So `init` can't be used for manual setting of TraceContext on passing the current `Execution` because at that point `RatpackCurrentTraceContext$TraceContextHolder` will be having the `CurrentTraceContext` and not `HttpTracing.class`

### PR DESCRIPTION
**Pull request by kirenjolly**
…rrent trace context on creating new spans, closes #14

### CODE REVIEW

**Comment by kirenjolly** [comment]
@llinder @adriancole @beckje01 Please review

**Comment by kirenjolly** [comment]
```TracingContextHolder``` is the one added to registry entry and that object gets updated each time a new span with scope is created . So ```HttpTracing``` won't be in registry entry 
```RegistryEntry{type=ratpack.zipkin.internal.RatpackCurrentTraceContext$TraceContextHolder, value=ratpack.zipkin.internal.RatpackCurrentTraceContext$TraceContextHolder@6139672b}```

**Comment by llinder** [comment]
Based on my understanding, as long as you are using the Guice module the HttpTracer should always be available on the Ratpack Execution via this binding [via this binding](https://github.com/openzipkin-contrib/brave-ratpack/blob/master/src/main/java/ratpack/zipkin/ServerTracingModule.java#L86).

Your suggested change seems fine, however I would still like to understand why it's failing for you and if we should pose a question or file a bug with Ratpack.  If you have a small example app that show this failing I can take a look and gather some feedback on possible causes.

**Comment by kirenjolly** [comment]
@llinder Yeah i can create a small example app to demonstrate this is failing.

**Comment by kirenjolly** [comment]
@llinder @beckje01 @adriancole  Can you take a look at this sample app where it is failing,
https://github.com/kirenjolly/ratpack-kotlin-demo
`HttpTracing.class` is found null in registry entries of the current execution.

**Comment by llinder** [comment]
Thanks for sharing the example.  The overall pattern and use of Guice Modules with Ratpack are a bit different than I have encountered before.  Also I honestly don't use Kotlin much so maybe I'm missing something :P In the `InitialHandler` I see a few things that are unusual and not surprising the log statements don't work as expected.  After a few tweaks things sort of start working though the forked Execution still doesn't have an instance of `HttpTracing`.

At this point I don't see harm in the proposed change you have in the PR so we will merge that and put the Guice + forked Execution context questions on the back burner.

**Review by llinder — APPROVED** [review]

**Comment by kirenjolly** [comment]
@llinder Can you give the link to snapshot you have published.

**Pull request merged**
