### PR TITLE
ensure the same span is available after parsing requests, closes #21

### LINKED ISSUE #21: Scope of the Span not working as expected with Ratpack Promises
### Scope of the Span not working as expected with Ratpack Promises

`newScope` function in `RatpackCurrentTraceContext`  has the `return()` which gets executed when scope of span closes when a promise is expected. But is scope is still not over.

### PR DESCRIPTION
**Pull request by drmaas**

### CODE REVIEW

**Comment by drmaas** [comment]
@llinder @adriancole

**Review by llinder — APPROVED** [review]
Thanks for the pull request with a test!  This seems like the correct thing to do and we should probably get this merged.  Still I would like to see how this pans out in practice before we do a full release.

**Comment by drmaas** [comment]
@llinder the only other thing is that there is no try/catch around the `spanInScope` now ... does that need to be retained, such that on an exception we ensure the span is closed?

**Comment by llinder** [comment]
@drmaas yes thats correct, we definitely want to guard against errors so we don't leak scope in the case of failures.

**Comment by drmaas** [comment]
@llinder updated with logic to close the scope immediately on exception.

**Comment by llinder** [comment]
@drmaas sorry if my comment was misleading... what I meant is that we should try to protect against any failures in the event `beforeSend` is never called.  Looking at the Ratpack code there doesn't seem to be any kind of `onError` for this so there might not be a way to guarantee closure in this case.

**Comment by llinder** [comment]
Distilling this down a bit I wrote similar test to yours @drmaas but things seem to be working as expected without changing the scope handling https://github.com/openzipkin-contrib/brave-ratpack/issues/21

Going to keep picking away at this and will update that PR if I can get an actual failure case.

**Comment by drmaas** [comment]
@llinder can you share that test case - the one I have in the PR failed with the prior code - I could see that the span was always closed before the request body was parsed, and hence prior to any code execution pertaining to the request. Try running this test case against  release`2.4.1`.

To be more clear, the issue was related to only requests with some payload to parse (via a `Promise`).

**Comment by drmaas** [comment]
@llinder in terms of error scenarios, the server will send almost always send a response (either via the handler or vi the server or client error handlers). The only time I can see it not responding is if there is some code blocking execution, the jvm shuts down, the network goes down, etc. 

If the network is done, the app will still *try* to send a response, and should still execute the `beforeSend` closure.

If the app freezes (causing eventual JVM shutdown) or JVM shuts down or a thread dies, then I am not sure how to ensure spans are closed. Perhaps this would be a separate feature. On JVM shutdown, is there a way to auto-close all active spans? If a thread dies, is there a way to close the span that was running on it?

**Comment by llinder** [comment]
What do you think about this: https://github.com/openzipkin-contrib/brave-ratpack/pull/24.  I pulled your original commit forward and changed the test a bit.   I'm not sure why I had problems with your original test not failing (probably some error on my part).  Anyway, I ended up working backwards to understand this better and rewrote the test to be a little more like other Brave instrumentation test.   Mind if we close out this PR and merge the one above?

**Comment by llinder** [comment]
As for the closing the scope on error, if the expectation is that Ratpack will always call `beforeSend` then I think we can forgo any additional exception handling.

**Comment by llinder** [comment]
Pulled the original changes from @drmaas to a new PR and adjusted the test a bit.  Opened a new PR here https://github.com/openzipkin-contrib/brave-ratpack/pull/24 and closing this one.

**Comment by drmaas** [comment]
Sounds good, thanks!

**Pull request closed without merging**
