### PR TITLE
issue-19: ensure only one trace context is in the registry.

### PR DESCRIPTION
**Pull request by llinder**
- the add method on the Ratpack RegistrySpec is additive in that it doesn't replace existing values but instead adds new values to a stack.
- small cleanup around the ExecInitializer to simplify logic

### CODE REVIEW

**Review by beckje01 — APPROVED** [review]

**Review by codefromthecrypt — APPROVED** [review]
less code too!

**Review by drmaas — APPROVED** [review]
Thanks for all of the fixes.

**Comment by kirenjolly** [comment]
@llinder @beckje01 @adriancole  Can you commit this changes to master and release a snapshot if all testing is done.
Because our tracing implementation is depending on this.

**Comment by llinder** [comment]
Before merging this I would like to get some tests in place.  While high level tests are passing it doesn't doesn't provide mush assurance some of these things are working or won't break in the future.   Assuming I can find a window of time today I will write some tests and if all goes well this will get merged.

**Comment by kirenjolly** [comment]
@llinder yeah it would be a great help if you could find some time to test it out today.

**Comment by kirenjolly** [comment]
@llinder Any updates?

**Comment by codefromthecrypt** [comment]
Github sends notification on updates. people add comments to issues when
there is an update.

this project is volunteer run. continual nagging sometimes demotivates
people. please be patient and wait for people to reply.

**Comment by llinder** [comment]
Added a few tests that should prove these changes do work as intended.

**Pull request merged**
